name: Cypress CI Pipeline

on:
  push:
    branches: [main, qw-187-tests-cypress]
  pull_request:
    branches: [main, qw-187-tests-cypress]

jobs:
  cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.14.0-chrome-145.0.7632.116-1-ff-148.0-edge-145.0.3800.70-1

    steps:
      - uses: actions/checkout@v3

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Caché de pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Asegurar binary de Cypress
        run: pnpm exec cypress install

      - name: Build del proyecto
        run: pnpm run build

      - name: Levantar servidor y ejecutar tests
        run: |
          pnpm run preview &
          SERVER_PID=$!
          sleep 10
          pnpm run cypress:run
          kill $SERVER_PID

      - name: Guardar artefactos de Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            screenshots
            videos